---
version: "3.8"
services:
  test:
    build:
      target: "test"
      context: "."
  terraform:
    env_file:
      - ".env"
    image: "hashicorp/terraform:latest"
    network_mode: "host"
    working_dir: "/usr/src/app"
    environment:
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      TF_TOKEN_app_terraform_io: "${TF_TOKEN_app_terraform_io}"
    volumes:
      - ".:/usr/src/app"
  cli:
    build:
      target: "cli"
      context: "."
    working_dir: "/usr/src/app"
    environment:
      ANSIBLE_COLLECTIONS_PATH: "/usr/share/ansible/collections"
      ANSIBLE_ROLES_PATH: "/usr/share/ansible/roles"
    volumes:
      - "./:/usr/src/app"
    image: "${CLI_IMAGE:-docker.io/h4ndzdatm0ld/ansible-eda:latest}"
    ports:
      - "5000:5000"
    command: "--rulebook rulebooks/rb-webhook-5000.yml -i inventories/dev/hosts.yml --verbose"
